spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    h2:
      console:
        enabled: true
  jwt:
    issuer: i-like-this-page
    secret: secret
