spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/i-like-this-page-db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
