# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI/CD

on:
  push:
    branches: [develop]

jobs:
  fe-ci-and-be-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm packages
        run: npm install
        working-directory: i-like-this-page-frontend

      - name: Build frontend and Copy to backend resources
        run: npm run deploy
        working-directory: i-like-this-page-frontend

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: i-like-this-page-backend

      - name: Copy production configuration from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          s3://iltp-deploy-bucket/application.yml src/main/resources/
        working-directory: i-like-this-page-backend

      - name: Test and Build with Gradle
        run: ./gradlew clean build
        working-directory: i-like-this-page-backend

      - name: Zip entire project directory
        run: zip -r iltp-backend *
        working-directory: i-like-this-page-backend

      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          iltp-backend.zip s3://iltp-deploy-bucket/
        working-directory: i-like-this-page-backend

      - name: Deploy zipped file from S3 to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name iltp \
          --deployment-group-name iltp-deploy-group \
          --s3-location bucket=iltp-deploy-bucket,bundleType=zip,key=iltp-backend.zip \
          --region ap-northeast-2
        working-directory: i-like-this-page-backend
